# Generated by Django 2.2.4 on 2019-08-20 11:27

from django.db import migrations

default_data = [
    {
        "name": "Arnaldo Pereira",
        "email": "arnaldo@luizalabs.com",
        "department": "Architecture",
    },
    {
        "name": "Renato Pedigoni",
        "email": "renato@luizalabs.com",
        "department": "E-commerce",
    },
    {
        "name": "Thiago Catoto",
        "email": "catoto@luizalabs.com",
        "department": "Mobile",
    },
]


def insert_data(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Department = apps.get_model('employee', 'Department')

    for item in default_data:
        department = Department.objects.create(name=item['department'])
        Employee.objects.create(
            name=item['name'], email=item['email'], department=department
        )


def delete_data(apps, schema_editor):
    Employee = apps.get_model('employee', 'Employee')
    Department = apps.get_model('employee', 'Department')

    for item in default_data:
        Employee.objects.filter(
            name=item['name'], email=item['email']
        ).delete()

        Department.objects.filter(name=item['department']).delete()


class Migration(migrations.Migration):

    dependencies = [('employee', '0001_initial')]

    operations = [migrations.RunPython(insert_data, reverse_code=delete_data)]
