# Generated by Django 2.2.4 on 2019-08-20 11:43

from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190820_1127'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
